version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ardhangini-be-app
    environment:
      - DB_HOST=192.168.0.26
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_DATABASE=ardhangini_db
      - DB_TYPE=postgres
      - DB_SYNCHRONIZE=true
    ports:
      - '3000:3000'
    #volumes:
    #  - ./src:/usr/app/src